# Configuratie tbv exporteerde formaten

# RSS-feed (Atom) - /atom.xml
[Atom]
  mediatype = "application/xml"
  baseName = "atom"
  noUgly = true

# JSON Feed: feed.json
[JSON]
  mediatype = "application/json"
  baseName = "feed"

# IndexNow-bestand: indexnow.json
[IndexNow]
  mediatype = "application/json"
  baseName = "indexnow"

# Calendar genereert een iCal-bestand voor evenementen
[Calendar]
  mediaType = "text/calendar"
  baseName = "calendar"

# Index voor zoekfunctionaliteit op de website
[SearchIndex]
  mediatype = "application/json"
  basename = "searchindex"

#[outputFormats.XMLEvent]
#  mediaType = "application/xml"
#  baseName = "schedule"

# EOF
