name = "NLUUG"
license = "MIT"
licenselink = "https://github.com/canhtran/maverick/blob/main/LICENSE"
description = "Based initially on Maverick, a minimal Hugo blog theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/canhtran/maverick"

# If you have a running demo of the theme.
# demosite = "https://maverick.canhtran.me"

tags = ["blog"]
features = ["ultra fast", "github comment", "responsive"]

# If the theme has a single author
[author]
    name = "Michael Boelen"
    homepage = "https://michaelboelen.com"
